### PR TITLE
Modify installation instructions

### PR DESCRIPTION
**Pull request by Akasurde**
Instructions are missing step to install requirements.txt using pip

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Review by ganeshrn — COMMENTED** [review]
As per @webknjaz the file name should end with `.in` extension. Also since it is build time dependency the file can be renamed as `requirements-dev.in`

**Comment by webknjaz** [comment]
@ganeshrn yep

**Comment by webknjaz** [comment]
But this can be done in a separate PR, no pressure here.

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
I'd probably use "build" instead of "dev" since it better reflects the purpose.

**Pull request merged**
